Restructure, cleanup

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -4,9 +4,35 @@ on:
   push:
     branches:
       - main
-    tags: [ "*" ]
 
 jobs:
+  create_tag:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Tag version
+        run: |
+          version=$(sed -nE 's/^version = "([0-9v\.]+)"/\1/p' pyproject.toml)
+          if [ -z "$version" ]; then
+            echo "Could not extract version."
+            exit 1
+          fi
+          echo "Extracted version '$version'."
+          if [ $(git tag -l "$version") ]; then
+            echo "Version tag already exists."
+            exit 1
+          fi
+          latest=$(git tag | tail -n 1)
+          printf '%s\n%s\n' "$latest" "$version" | sort -V -C
+          if [ $? -eq 1 ]; then
+            echo "Version tag precedes latest ($latest)."
+            exit 1
+          fi
+          echo "Creating release..."
+          curl -X POST \
+            -H "Authorization: token $GITHUB_TOKEN" \
+            "https://api.github.com/repos/$GITHUB_REPOSITORY/releases" \
+            -d '{"tag_name": "$version", "name": "$version"}'
+          echo "Done!"
   build:
     runs-on: ubuntu-latest
     steps:
@@ -28,6 +54,7 @@ jobs:
     runs-on: ubuntu-latest
     needs:
       - build
+      - create_tag
     environment:
       name: pypi
       url: https://pypi.org/p/qc-parallelizer
